### PR TITLE
Created some initial cookbook entries

### PR DESCRIPTION
**Pull request by peastman**
This is the start of what will eventually become the OpenMM cookbook.  See https://github.com/openmm/openmm/issues/3140.

### CODE REVIEW

**Comment by jchodera** [comment]
How do these get tested by CI?

**Comment by peastman** [comment]
Currently they don't, but that's something we'll want to implement in the future both for the cookbook and the tutorials.

**Comment by peastman** [comment]
This is my initial batch of entries.  Comments would be great, and also suggestions for other entries.

**Comment by peastman** [comment]
If no one has any comments, shall I merge this?  Then we need to figure out how to organize and display them.

**Pull request merged**
