### PR TITLE
Updated benchmarks for 7.7

### PR DESCRIPTION
**Pull request by peastman**
I reran the benchmarks for 7.7 and moved the full set over to the main site.  You can preview this at https://peastman.github.io/openmm-org/benchmarks.

### CODE REVIEW

**Review by jchodera — APPROVED** [review]
Looks good!

It looks reasonably straightforward for me to integrate a few more GPUs (A10, A40, GTX-2080Ti, GTX-2080, V100).

Eventually, perhaps we want to use a different JSON format that would allow new GPU statistics to be added by just adding a machine-generated block, rather than manually editing the JSON file and making sure not to mess up any columns?

**Comment by peastman** [comment]
If you want to run these benchmarks on any other GPUs, here are the exact commands to use.

```
python benchmark.py --platform=CUDA --seconds=30 --test=gbsa
python benchmark.py --platform=CUDA --seconds=30 --test=rf
python benchmark.py --platform=CUDA --seconds=30 --test=pme
python benchmark.py --platform=CUDA --seconds=30 --test=apoa1rf
python benchmark.py --platform=CUDA --seconds=30 --test=apoa1pme
python benchmark.py --platform=CUDA --seconds=30 --test=apoa1ljpme
python benchmark.py --platform=CUDA --seconds=30 --test=amber20-cellulose
python benchmark.py --platform=CUDA --seconds=30 --test=amber20-stmv
python benchmark.py --platform=CUDA --seconds=30 --test=amoebagk --polarization=mutual
python benchmark.py --platform=CUDA --seconds=30 --test=amoebapme --polarization=mutual
```

For running the CPU benchmarks, here are the commands.

```
python benchmark.py --platform=CPU --seconds=30 --test=gbsa
python benchmark.py --platform=CPU --seconds=30 --test=rf
python benchmark.py --platform=CPU --seconds=30 --test=pme --pme-cutoff=0.8
python benchmark.py --platform=CPU --seconds=30 --test=apoa1rf --pme-cutoff=0.8
python benchmark.py --platform=CPU --seconds=30 --test=apoa1pme --pme-cutoff=0.8
python benchmark.py --platform=CPU --seconds=30 --test=apoa1ljpme --pme-cutoff=0.8
```

**Comment by jchodera** [comment]
Presumably, this should be something we add an option for (e.g. `--website-benchmarks`) to automate in https://github.com/openmm/openmm/pull/3386 as well?

**Comment by jchodera** [comment]
Thanks! I'll open a PR to add additional benchmarks after this is merged.

**Comment by peastman** [comment]
There isn't a single set of website benchmarks.  Are you running the benchmarks for a single NVIDIA CPU?  A single AMD GPU?  A CPU?  Benchmarks for parallelizing across multiple GPUs?  Each one is a different set of benchmarks.

As much as possible, though, the default values for all options should match the posted benchmarks.  The one main exception is reducing `pme-cutoff` on the CPU platform.

**Comment by jchodera** [comment]
> There isn't a single set of website benchmarks. Are you running the benchmarks for a single NVIDIA CPU? A single AMD GPU? A CPU? Benchmarks for parallelizing across multiple GPUs? Each one is a different set of benchmarks.

That's four different classes of benchmarks. How about something like
`--website-benchmarks { gpu | cpu | multi-gpu }`?

> As much as possible, though, the default values for all options should match the posted benchmarks. The one main exception is reducing pme-cutoff on the CPU platform.

Why is this an exception?

**Comment by jchodera** [comment]
If you'd rather integrate benchmarks into this PR, here are some more:

<details>

<summary>NVIDIA RTX2080Ti</summary>
```
+ python benchmark.py --platform=CUDA --seconds=30 --test=gbsa
Platform: CUDA
Precision: single

Test: gbsa
Ensemble: NVT
Step Size: 4 fs
Integrated 199405 steps in 28.1044 seconds
2452.08 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=rf
Platform: CUDA
Precision: single

Test: rf
Ensemble: NVT
Step Size: 4 fs
Integrated 115504 steps in 28.9407 seconds
1379.31 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=pme
Platform: CUDA
Precision: single

Test: pme (cutoff=0.9)
Ensemble: NVT
Step Size: 4 fs
Integrated 92339 steps in 28.126 seconds
1134.62 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=apoa1rf
Platform: CUDA
Precision: single

Test: apoa1rf
Ensemble: NVT
Step Size: 4 fs
Integrated 34859 steps in 29.1657 seconds
413.063 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=apoa1pme
Platform: CUDA
Precision: single

Test: apoa1pme
Ensemble: NVT
Step Size: 4 fs
Integrated 24825 steps in 29.6981 seconds
288.891 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=apoa1ljpme
Platform: CUDA
Precision: single

Test: apoa1ljpme
Ensemble: NVT
Step Size: 4 fs
Integrated 19613 steps in 29.1614 seconds
232.439 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=amber20-cellulose
Platform: CUDA
Precision: single

Test: amber20-cellulose
Ensemble: NVT
Step Size: 4 fs
Integrated 4417 steps in 30.2919 seconds
50.3935 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=amber20-stmv
Platform: CUDA
Precision: single

Test: amber20-stmv
Ensemble: NVT
Step Size: 4 fs
Integrated 1009 steps in 24.5931 seconds
14.1792 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=amoebagk --polarization=mutual
Platform: CUDA
Precision: single

Test: amoebagk (epsilon=1e-05)
Ensemble: NVT
Step Size: 2 fs
Integrated 3727 steps in 29.4412 seconds
21.875 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=amoebapme --polarization=mutual
Platform: CUDA
Precision: single

Test: amoebapme (epsilon=1e-05)
Ensemble: NVT
Step Size: 2 fs
Integrated 3558 steps in 30.0402 seconds
20.4667 ns/day
```
</details>

<details>

<summary>NVIDIA V100</summary>

```
+ python benchmark.py --platform=CUDA --seconds=30 --test=gbsa
Platform: CUDA
Precision: single

Test: gbsa
Ensemble: NVT
Step Size: 4 fs
Integrated 199405 steps in 28.1044 seconds
2452.08 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=rf
Platform: CUDA
Precision: single

Test: rf
Ensemble: NVT
Step Size: 4 fs
Integrated 115504 steps in 28.9407 seconds
1379.31 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=pme
Platform: CUDA
Precision: single

Test: pme (cutoff=0.9)
Ensemble: NVT
Step Size: 4 fs
Integrated 92339 steps in 28.126 seconds
1134.62 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=apoa1rf
Platform: CUDA
Precision: single

Test: apoa1rf
Ensemble: NVT
Step Size: 4 fs
Integrated 34859 steps in 29.1657 seconds
413.063 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=apoa1pme
Platform: CUDA
Precision: single

Test: apoa1pme
Ensemble: NVT
Step Size: 4 fs
Integrated 24825 steps in 29.6981 seconds
288.891 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=apoa1ljpme
Platform: CUDA
Precision: single

Test: apoa1ljpme
Ensemble: NVT
Step Size: 4 fs
Integrated 19613 steps in 29.1614 seconds
232.439 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=amber20-cellulose
Platform: CUDA
Precision: single

Test: amber20-cellulose
Ensemble: NVT
Step Size: 4 fs
Integrated 4417 steps in 30.2919 seconds
50.3935 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=amber20-stmv
Platform: CUDA
Precision: single

Test: amber20-stmv
Ensemble: NVT
Step Size: 4 fs
Integrated 1009 steps in 24.5931 seconds
14.1792 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=amoebagk --polarization=mutual
Platform: CUDA
Precision: single

Test: amoebagk (epsilon=1e-05)
Ensemble: NVT
Step Size: 2 fs
Integrated 3727 steps in 29.4412 seconds
21.875 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=amoebapme --polarization=mutual
Platform: CUDA
Precision: single

Test: amoebapme (epsilon=1e-05)
Ensemble: NVT
Step Size: 2 fs
Integrated 3558 steps in 30.0402 seconds
20.4667 ns/day
(openmm-7.7) [chodera@lilac:examples]$ cat benchmarks-V100 
+ python benchmark.py --platform=CUDA --seconds=30 --test=gbsa
Platform: CUDA
Precision: single

Test: gbsa
Ensemble: NVT
Step Size: 4 fs
Integrated 179642 steps in 28.3327 seconds
2191.26 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=rf
Platform: CUDA
Precision: single

Test: rf
Ensemble: NVT
Step Size: 4 fs
Integrated 118595 steps in 28.7276 seconds
1426.73 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=pme
Platform: CUDA
Precision: single

Test: pme (cutoff=0.9)
Ensemble: NVT
Step Size: 4 fs
Integrated 87027 steps in 30.1063 seconds
999.01 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=apoa1rf
Platform: CUDA
Precision: single

Test: apoa1rf
Ensemble: NVT
Step Size: 4 fs
Integrated 45229 steps in 29.8121 seconds
524.321 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=apoa1pme
Platform: CUDA
Precision: single

Test: apoa1pme
Ensemble: NVT
Step Size: 4 fs
Integrated 27922 steps in 29.5141 seconds
326.957 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=apoa1ljpme
Platform: CUDA
Precision: single

Test: apoa1ljpme
Ensemble: NVT
Step Size: 4 fs
Integrated 21569 steps in 30.2019 seconds
246.814 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=amber20-cellulose
Platform: CUDA
Precision: single

Test: amber20-cellulose
Ensemble: NVT
Downloading https://ambermd.org/Amber20_Benchmark_Suite.tar.gz
Extracting Amber20_Benchmark_Suite.tar.gz
Step Size: 4 fs
Integrated 5394 steps in 29.0443 seconds
64.1836 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=amber20-stmv
Platform: CUDA
Precision: single

Test: amber20-stmv
Ensemble: NVT
Step Size: 4 fs
Integrated 1540 steps in 26.5682 seconds
20.0324 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=amoebagk --polarization=mutual
Platform: CUDA
Precision: single

Test: amoebagk (epsilon=1e-05)
Ensemble: NVT
Step Size: 2 fs
Integrated 3855 steps in 28.8549 seconds
23.086 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=amoebapme --polarization=mutual
Platform: CUDA
Precision: single

Test: amoebapme (epsilon=1e-05)
Ensemble: NVT
Step Size: 2 fs
Integrated 3488 steps in 29.5474 seconds
20.3986 ns/day
```
</details>

**Comment by peastman** [comment]
> Why is this an exception?

The PME cutoff is chosen to optimized performance.  In practice 0.9 nm tends to be fastest on the CUDA and OpenCL platforms, but 0.8 nm tends to be faster on the CPU platform.  That's not guaranteed, though, and might vary depending on the number of CPU cores.  It needs to be tested for any new CPU you haven't run benchmarks on before.

**Comment by jchodera** [comment]
I've provided a number of other benchmarks in https://github.com/openmm/openmm-org/pull/86#issuecomment-1005264753 if you want to include them here, @peastman.

> The PME cutoff is chosen to optimized performance. In practice 0.9 nm tends to be fastest on the CUDA and OpenCL platforms, but 0.8 nm tends to be faster on the CPU platform. That's not guaranteed, though, and might vary depending on the number of CPU cores. It needs to be tested for any new CPU you haven't run benchmarks on before.

Why don't we optimize the cutoff on every platform individually (or dynamically)? If it's a big enough effect to matter, we should be automatically optimizing it, shouldn't we?

**Comment by peastman** [comment]
Because I only ever run the official benchmarks on a handful of machines, which are consistent from one release to the next so we can track changes in performance over time.  I've never seen a GPU where a cutoff different from 0.9 was faster, so this consideration is mainly just for the CPU platform, and I've been using the same computer for the CPU benchmarks for a few years.  It also happens to be the computer I use for doing optimization work on the CPU platform, so I'm pretty familiar with its performance characteristics.

**Comment by jchodera** [comment]
> I've never seen a GPU where a cutoff different from 0.9 was faster

Here's an NVIDIA A10:
```
(openmm-7.7) [msk@csctmp-r750xa-5 examples]$ python benchmark.py --platform=CUDA --seconds=30 --test=pme --pme-cutoff=0.8
Platform: CUDA
Precision: single

Test: pme (cutoff=0.8)
Ensemble: NVT
Step Size: 4 fs
Integrated 107959 steps in 30.4457 seconds
1225.48 ns/day
(openmm-7.7) [msk@csctmp-r750xa-5 examples]$ python benchmark.py --platform=CUDA --seconds=30 --test=pme --pme-cutoff=0.9
Platform: CUDA
Precision: single

Test: pme (cutoff=0.9)
Ensemble: NVT
Step Size: 4 fs
Integrated 100047 steps in 30.3645 seconds
1138.71 ns/day
```
Now you have! :)

**Comment by jchodera** [comment]
Same thing on an A40, though the improvement isn't as substantial (5% on the A40 instead of 8% on the A10):
```
(openmm-7.7) [msk@csctmp-r750xa-4 examples]$ python benchmark.py --platform=CUDA --seconds=30 --test=pme --pme-cutoff=0.8
Platform: CUDA
Precision: single

Test: pme (cutoff=0.8)
Ensemble: NVT
Step Size: 4 fs
Integrated 123329 steps in 30.0794 seconds
1417 ns/day
(openmm-7.7) [msk@csctmp-r750xa-4 examples]$ python benchmark.py --platform=CUDA --seconds=30 --test=pme --pme-cutoff=0.9
Platform: CUDA
Precision: single

Test: pme (cutoff=0.9)
Ensemble: NVT
Step Size: 4 fs
Integrated 117616 steps in 30.01 seconds
1354.49 ns/day
```

**Comment by jchodera** [comment]
Interestingly enough, there's almost no difference between the two cutoffs on an 80-thread Intel(R) Xeon(R) Platinum 8380 CPU @ 2.30GHz:
```
(openmm-7.7) [msk@csctmp-r750xa-5 examples]$ python benchmark.py --platform=CPU --seconds=30 --test=pme --pme-cutoff=0.8
Platform: CPU

Test: pme (cutoff=0.8)
Ensemble: NVT
Step Size: 4 fs
Integrated 2460 steps in 30.178 seconds
28.1721 ns/day
(openmm-7.7) [msk@csctmp-r750xa-5 examples]$ python benchmark.py --platform=CPU --seconds=30 --test=pme --pme-cutoff=0.9
Platform: CPU

Test: pme (cutoff=0.9)
Ensemble: NVT
Step Size: 4 fs
Integrated 2411 steps in 29.8934 seconds
27.8737 ns/day
```

**Comment by jchodera** [comment]
@peastman : Do you want to integrate some of [these benchmarks](https://github.com/openmm/openmm-org/pull/86#issuecomment-1005264753) and then merge?

**Comment by peastman** [comment]
> Interestingly enough, there's almost no difference between the two cutoffs on an 80-thread Intel(R) Xeon(R) Platinum 8380 CPU @ 2.30GHz:

In that case, I suspect it's just dominated by overhead.  It's slower on that 80 thread monster than on my four core workstation!  Reducing the number of threads would probably make it faster.

**Comment by jchodera** [comment]
> In that case, I suspect it's just dominated by overhead. It's slower on that 80 thread monster than on my four core workstation! Reducing the number of threads would probably make it faster.

Yet another thing we should auto-tune if it has that big of an impact. These differences are as large or larger than some of the performance improvements obtained from significant code optimization, so it seems weird to leave them on the table.

On this particular CPU, performance seems to keep increasing up to at least 32 threads, and 9A cutoff becomes faster than 8A at around 16 threads:
<details>

<summary>Intel(R) Xeon(R) Platinum 8380 CPU @ 2.30GHz</summary>

```
(openmm-7.7) [msk@csctmp-r750xa-5 examples]$ OPENMM_CPU_THREADS=4 python benchmark.py --platform=CPU --seconds=30 --test=pme --pme-cutoff=0.8
Platform: CPU

Test: pme (cutoff=0.8)
Ensemble: NVT
Step Size: 4 fs
Integrated 1268 steps in 28.557 seconds
15.3455 ns/day
(openmm-7.7) [msk@csctmp-r750xa-5 examples]$ OPENMM_CPU_THREADS=4 python benchmark.py --platform=CPU --seconds=30 --test=pme --pme-cutoff=0.9
Platform: CPU

Test: pme (cutoff=0.9)
Ensemble: NVT
Step Size: 4 fs
Integrated 1276 steps in 30.9736 seconds
14.2375 ns/day
(openmm-7.7) [msk@csctmp-r750xa-5 examples]$ OPENMM_CPU_THREADS=8 python benchmark.py --platform=CPU --seconds=30 --test=pme --pme-cutoff=0.8
Platform: CPU

Test: pme (cutoff=0.8)
Ensemble: NVT
Step Size: 4 fs
Integrated 2080 steps in 30.3223 seconds
23.7069 ns/day
(openmm-7.7) [msk@csctmp-r750xa-5 examples]$ OPENMM_CPU_THREADS=8 python benchmark.py --platform=CPU --seconds=30 --test=pme --pme-cutoff=0.9
Platform: CPU

Test: pme (cutoff=0.9)
Ensemble: NVT
Step Size: 4 fs
Integrated 2033 steps in 32.6268 seconds
21.5346 ns/day
(openmm-7.7) [msk@csctmp-r750xa-5 examples]$ OPENMM_CPU_THREADS=16 python benchmark.py --platform=CPU --seconds=30 --test=pme --pme-cutoff=0.8
Platform: CPU

Test: pme (cutoff=0.8)
Ensemble: NVT
Step Size: 4 fs
Integrated 2834 steps in 30.1406 seconds
32.4953 ns/day
(openmm-7.7) [msk@csctmp-r750xa-5 examples]$ OPENMM_CPU_THREADS=16 python benchmark.py --platform=CPU --seconds=30 --test=pme --pme-cutoff=0.9
Platform: CPU

Test: pme (cutoff=0.9)
Ensemble: NVT
Step Size: 4 fs
Integrated 3146 steps in 33.8551 seconds
32.115 ns/day
(openmm-7.7) [msk@csctmp-r750xa-5 examples]$ OPENMM_CPU_THREADS=32 python benchmark.py --platform=CPU --seconds=30 --test=pme --pme-cutoff=0.8
Platform: CPU

Test: pme (cutoff=0.8)
Ensemble: NVT
Step Size: 4 fs
Integrated 3004 steps in 31.042 seconds
33.4444 ns/day
(openmm-7.7) [msk@csctmp-r750xa-5 examples]$ OPENMM_CPU_THREADS=32 python benchmark.py --platform=CPU --seconds=30 --test=pme --pme-cutoff=0.9
Platform: CPU

Test: pme (cutoff=0.9)
Ensemble: NVT
Step Size: 4 fs
Integrated 3417 steps in 30.8695 seconds
38.2551 ns/day
```

</details>

**Comment by peastman** [comment]
I added the benchmarks for the other GPUs.  Looking over the results, it's kind of interesting.  The one consistent result is that RTX 2080 is the slowest GPU in every case, often by a large margin.  Aside from that, it varies a lot.  On the smaller benchmarks, there isn't a lot of variation in speed.  In some cases, the A100 is actually slower than the much older and less expensive Volta cards.  But when you get up to the really big systems, it crushes everything else, including the other Ampere cards.

**Comment by peastman** [comment]
The [PME optimizer](https://simtk.org/svn/pyopenmm/trunk/simtk/pyopenmm/extras/optimizepme.py) script I wrote years ago does a more sophisticated job of optimizing the cutoff.  It takes advantage of the fact that as you increase the cutoff, the direct space part continuously gets slower, but the reciprocal space part gets faster in discrete jumps whenever the grid size becomes smaller.  It also tests with and without running PME on the CPU.  In practice, that's only useful on low end GPUs.  On more powerful GPUs, it tends to be much slower.

We could integrate this logic into the benchmarking script to provide an autotune option.  For the CPU platform, running all combinations of cutoff and number of threads could take quite a while for each benchmark.

**Comment by jchodera** [comment]
> I added the benchmarks for the other GPUs. Looking over the results, it's kind of interesting. The one consistent result is that RTX 2080 is the slowest GPU in every case, often by a large margin. Aside from that, it varies a lot. On the smaller benchmarks, there isn't a lot of variation in speed. In some cases, the A100 is actually slower than the much older and less expensive Volta cards. But when you get up to the really big systems, it crushes everything else, including the other Ampere cards.

I was certainly surprised by the A10/A40 results! I'd love to have RTX 30x0 / 30x0 Ti results, but we don't have access to any of these cards, and I imagine not many other folks do either.

The page looks great now! If you can go ahead and deploy it, we can merge it.

Looking forward to getting benchmarks on a very large variety of consumer cards once @jcoffland gets the FAH core22 0.0.19 (already built by @dotsdl) deployed on Jan 8.

**Comment by jchodera** [comment]
> The PME optimizer script I wrote years ago does a more sophisticated job of optimizing the cutoff. It takes advantage of the fact that as you increase the cutoff, the direct space part continuously gets slower, but the reciprocal space part gets faster in discrete jumps whenever the grid size becomes smaller. It also tests with and without running PME on the CPU. In practice, that's only useful on low end GPUs. On more powerful GPUs, it tends to be much slower.
> 
> We could integrate this logic into the benchmarking script to provide an autotune option. For the CPU platform, running all combinations of cutoff and number of threads could take quite a while for each benchmark.

This is a good idea, though I wonder if (1) we can offer it through `openmm.app` to make it extremely easy to integrate into user workflows, and (2) we can come up with an 80/20 approach to rapidly optimizing a few things at the start of a simulation that will quickly net most users most of the benefits. One idea, for example, is to just have `Simulation` have an `autotune=True` that would spend a few seconds at the beginning doing some brief optimization. But it would be better if we could think of more tightly integrated ways to deliver tuning benefits in a more streamlined fashion.

I'll open another issue to discuss.

**Comment by jchodera** [comment]
Tweet announcing the benchmarks update is here: https://twitter.com/openmm_toolkit/status/1479190648141926401

**Comment by jchodera** [comment]
Following [this twitter comment](https://twitter.com/scottlegrand/status/1479202949783953410), I re-ran the A100 benchmarks on an NVIDIA A100 80GB PCIe. It shows a bit of a performance improvement for the DHFR PME system (1153 -> 1239 ns/day). Some other benchmarks seem to improve as well. Maybe we want to update these?

<details>

<summary>A100 80GB benchmarks</summary>

```
+ python benchmark.py --platform=CUDA --seconds=30 --test=gbsa
Platform: CUDA
Precision: single

Test: gbsa
Ensemble: NVT
Step Size: 4 fs
Integrated 168958 steps in 29.9765 seconds
1947.92 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=rf
Platform: CUDA
Precision: single

Test: rf
Ensemble: NVT
Step Size: 4 fs
Integrated 122867 steps in 29.9765 seconds
1416.54 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=pme
Platform: CUDA
Precision: single

Test: pme (cutoff=0.9)
Ensemble: NVT
Step Size: 4 fs
Integrated 107771 steps in 30.0415 seconds
1239.81 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=apoa1rf
Platform: CUDA
Precision: single

Test: apoa1rf
Ensemble: NVT
Step Size: 4 fs
Integrated 52179 steps in 30.2669 seconds
595.801 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=apoa1pme
Platform: CUDA
Precision: single

Test: apoa1pme
Ensemble: NVT
Step Size: 4 fs
Integrated 38828 steps in 30.0263 seconds
446.907 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=apoa1ljpme
Platform: CUDA
Precision: single

Test: apoa1ljpme
Ensemble: NVT
Step Size: 4 fs
Integrated 30473 steps in 30.0244 seconds
350.764 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=amber20-cellulose
Platform: CUDA
Precision: single

Test: amber20-cellulose
Ensemble: NVT
Downloading https://ambermd.org/Amber20_Benchmark_Suite.tar.gz
Extracting Amber20_Benchmark_Suite.tar.gz
Step Size: 4 fs
Integrated 9324 steps in 29.928 seconds
107.671 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=amber20-stmv
Platform: CUDA
Precision: single

Test: amber20-stmv
Ensemble: NVT
Step Size: 4 fs
Integrated 2659 steps in 28.259 seconds
32.5189 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=amoebagk --polarization=mutual
Platform: CUDA
Precision: single

Test: amoebagk (epsilon=1e-05)
Ensemble: NVT
Step Size: 2 fs
Integrated 5078 steps in 29.4344 seconds
29.8113 ns/day
+ python benchmark.py --platform=CUDA --seconds=30 --test=amoebapme --polarization=mutual
Platform: CUDA
Precision: single

Test: amoebapme (epsilon=1e-05)
Ensemble: NVT
Step Size: 2 fs
Integrated 4134 steps in 29.698 seconds
24.054 ns
```

</details>

This may be a clocking issue, so here is what `nvidia-smi -q` says about clocks on this machine:
```
    Clocks
        Graphics                          : 1410 MHz
        SM                                : 1410 MHz
        Memory                            : 1512 MHz
        Video                             : 1275 MHz
    Applications Clocks
        Graphics                          : 1410 MHz
        Memory                            : 1512 MHz
    Default Applications Clocks
        Graphics                          : 1410 MHz
        Memory                            : 1512 MHz
    Max Clocks
        Graphics                          : 1410 MHz
        SM                                : 1410 MHz
        Memory                            : 1512 MHz
        Video                             : 1290 MHz
```

**Comment by jchodera** [comment]
The A40 appears to be clocked higher:
```
   Clocks
        Graphics                          : 1740 MHz
        SM                                : 1740 MHz
        Memory                            : 7250 MHz
        Video                             : 1530 MHz
    Applications Clocks
        Graphics                          : 1740 MHz
        Memory                            : 7251 MHz
    Default Applications Clocks
        Graphics                          : 1740 MHz
        Memory                            : 7251 MHz
    Max Clocks
        Graphics                          : 1740 MHz
        SM                                : 1740 MHz
        Memory                            : 7251 MHz
        Video                             : 1530 MHz
    Max Customer Boost Clocks
        Graphics                          : 1740 MHz
```

**Comment by jchodera** [comment]
The first posted benchmarks tweet has been viewed about 16,000 times already, with 89 people clicking through to complete benchmarks:
image

I think this indicates that the OpenMM twitter account (now with 1,571 followers) is a reasonably useful way to reach a significant amount of users.

**Comment by CoryKornowicz** [comment]
Question about benchmarks, where does the Charmm DRUDE polarizable forcefield fall in? And are it’s forces comparable in accuracy to the Ameoba polarized implementation?

**Comment by peastman** [comment]
I'm not sure of specific studies about its accuracy.  I'd expect it to be somewhere in between standard force fields and AMOEBA.  Same for speed.

**Pull request merged**
