### PR TITLE
Redesigned home page

### PR DESCRIPTION
**Pull request by peastman**
This PR is based on https://github.com/openmm/openmm-org/pull/45, replacing the home page with a modified version.  You can try it out at http://peastman.github.io/openmm-org/.

There was one thing I wasn't sure how to do.  When you click on the "Highly Optimized" box, it should switch to the Benchmarks tab.  How do I do that?

### CODE REVIEW

**Comment by jchodera** [comment]
This is looking good!

Some comments:

There are a few important things to put up top here that are missing from the current header:
image
* Free and open source
* GPU-accelerated
* molecular simulation library and application
* Python-enabled

Except for the ribbon (which my brain is still not used to paying attention to), I can't see how to get to the source code or GitHub page:
image
I also wouldn't know where to click to install or get started. Should there be something more obvious like "Installing" or "Getting Started"?

There's an "Easy Installation" card, but it's not obvious it's clickable. If there was a hotlink in there (blue underlined text), it would be more obvious. Or is there some other way to make it clear it's clickable (other than passing your mouse over)?

**Comment by peastman** [comment]
> Should there be something more obvious like "Installing" or "Getting Started"?

You mean like the section of the page entitled, "Installation"? :)  (I know, it's that "above the fold" thing.  If something isn't visible without scrolling, people can miss that it's there.)

**Comment by jchodera** [comment]
Restoring these elements would also be helpful!
image

**Comment by jchodera** [comment]
> You mean like the section of the page entitled, "Installation"? :) (I know, it's that "above the fold" thing. If something isn't visible without scrolling, people can miss that it's there.)

I must be blind...where is that?
image

**Comment by jchodera** [comment]
Oh!
image
Yeah, nobody will see that.

**Comment by peastman** [comment]
Also, thank you for beautifully illustrating my point about things above the navigation bar being invisible:

> Except for the ribbon (which my brain is still not used to paying attention to), I can't see how to get to the source code or GitHub page:

It's not the user's job to learn to pay attention to it.  It's the designer's job to put the information where the user *will* see it!

Let me experiment and see what I can do.  I was trying to make the layout as similar as possible to the rest of the site, but clearly it isn't working.  We have a lot of wasted space, both in the header and in the margins, and that's pushing too much of the important content off the bottom.

**Comment by peastman** [comment]
@raimis how do I adjust the page margins?  I've been searching for where that's set, so far without success!

**Comment by peastman** [comment]
Never mind, I figured it out!

**Comment by peastman** [comment]
> Restoring these elements would also be helpful!

Where are you seeing those elements?  I don't think I changed any code related to them.  And I just checked the version @raimis created and I don't see them on the original version either.

**Comment by peastman** [comment]
New version up.  On any decent sized screen, it should now display all four boxes in a single row.  I also made a lot of other minor changes to wording and spacing, and added a "get the source" section.  And it now displays better on phones and other small screens (the header was kind of broken before).

**Comment by jchodera** [comment]
image
Perhaps we can change the text from:

> OpenMM can be easily installed with Conda package manager:

to

> OpenMM can be easily installed from [conda-forge](https://conda-forge.org/) using the [conda package manager](https://docs.conda.io/):

so that folks who don't know about either can find out more information by clicking on the links?

**Comment by jchodera** [comment]
> On any decent sized screen, it should now display all four boxes in a single row. 

@peastman : It's still not clear that you should/can click on these boxes to get more information. Is there some other way to communicate that you can, like making the titles render in link text style, or making something that resembles a button?

**Comment by jchodera** [comment]
Actually, these aren't even all buttons---clicking on "Highly optimized" does nothing.
We now have four panels that use identical design language but behave in two different ways:
image

**Comment by jchodera** [comment]
image
Link "User Guide" to the user guide?

**Comment by peastman** [comment]
I said up at the very top

> There was one thing I wasn't sure how to do. When you click on the "Highly Optimized" box, it should switch to the Benchmarks tab. How do I do that?

I'm just waiting for @raimis to tell me how to do it.

The boxes highlight when you pass the mouse over them, which is a standard way to indicate you can click on them.  Most of the other tabs also have clickable boxes just like these.  But if the user doesn't realize, it isn't important.  I made them clickable because clicking on them seemed like an obvious thing to do.  But they're never the only way of getting the information: the "Installation" section has another link to the installation instructions, and the tab bar already has links to the benchmarks and documentation.

**Comment by raimis** [comment]
> I'm just waiting for @raimis to tell me how to do it.

I don't have a concrete answer. A general solution would be to use Vue Router, but https://github.com/openmm/openmm-org/pull/45#issuecomment-852019985. Alternatively, it should be possible to do that with the custom events (https://vuejs.org/v2/guide/components-custom-events.html).

**Comment by peastman** [comment]
I've never worked with Vue before, so I'm still just trying to grasp some of the basics.  I can add a `v-on:click` attribute to the `<v-card>`, but what should the script do?

[This page](https://www.reddit.com/r/vuetifyjs/comments/hfdf5i/how_to_programmatically_change_tabs_in_vuetify/) looks relevant, but I don't entirely understand it.  And [this one](https://jareklipski.medium.com/linking-to-a-specific-tab-in-vuetify-js-d978525f2e1a) presents a method that looks very easy, but it uses Vue Router, which you said isn't compatible.

**Comment by peastman** [comment]
I figured it out.  What I ended up doing is amazingly simple, much simpler than any of the pages I was looking at.  That makes me wonder if I'm missing something!  @raimis could you take a look and see if it looks ok?

**Comment by jchodera** [comment]
I believe merging will deploy, right?

Is it OK if I solicit feedback on twitter on how we can make the page more useful to our users after it goes live?

**Comment by peastman** [comment]
Sounds good!

**Comment by peastman** [comment]
Yes, it sounds like a good idea.  Still. :)

**Comment by peastman** [comment]
Have you gotten any feedback?

**Comment by jchodera** [comment]
No responses to the tweet:
https://twitter.com/openmm_toolkit/status/1403458541977882627

**Comment by peastman** [comment]
Should we merge this, or is there anything else we want to do first?

**Comment by jchodera** [comment]
Let's go for it, and see what people think!
I'd just be careful to understand what we would need to do to revert in case things break.

**Comment by peastman** [comment]
Ok, I'll merge this.  If we need to roll back, that *should* just be a matter of reverting this PR.

**Pull request merged**
