### PR TITLE
change tutorials to link to cookbook webpage

### PR DESCRIPTION
**Pull request by sef43**
as discussed in https://github.com/openmm/openmm-cookbook/issues/14 this changes the tutorials section to link to the tutorials on the cookbook webpage, and adds link to the cookbook and tutorials in the documentation section.

deployment can be seen here: https://sef43.github.io/openmm-org/

### CODE REVIEW

**Comment by peastman** [comment]
I think we should just remove the Tutorials tab.  It no longer serves any purpose.

**Comment by sef43** [comment]
I have removed the tutorials tab

**Comment by peastman** [comment]
I see you added the cookbook and tutorials to the development docs section.  What's the workflow for managing them?  They aren't tied to a release in the same way the rest of the documentation is.  When do the development versions get built, and when do they get promoted to latest?

**Comment by sef43** [comment]
Yes that is true, the cookbook has its own release cycle, the main branch of the cookbook is automatically deployed to githubpages as the cookbook/dev/ . It is promoted to latest when a release is done on the cookbook github repo.

We can remove the links to the dev versions from here and just leave the latest versions if you think that is better?

**Pull request merged**
