### PR TITLE
Updates to website

### PR DESCRIPTION
**Pull request by peastman**
The biggest change is adding a list of consortium members.  I've also made various minor updates.

### CODE REVIEW

**Comment by jchodera** [comment]
Would it be useful to add affiliations or links to their pages?

**Comment by peastman** [comment]
I could add affiliations, if you think that's useful.  I don't know what pages people would want it to link to, so if we want to add links I'd need to contact everyone to ask.

**Comment by jchodera** [comment]
OK, this looks good, thanks!

**Comment by peastman** [comment]
I'm not sure why it's displaying the list of members as if they were links...

**Comment by jchodera** [comment]
Let me take a stab at this.

**Comment by jchodera** [comment]
I've been playing with this locally and can't figure out how to tweak it to change the colors. I've managed to improve on this slightly, though---will open a PR.

**Pull request merged**
